### PR TITLE
fix build incompatibility with predef NOP macro

### LINKED ISSUE #29: Firmware build incompatible with NOP()-defining header (SDCC 3.7.0)
When building with Fedora 29 / sdcc-3.7.0-1.fc29:
```
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` -DIMME -c cc1111_aes.c
In file included from include/chipcon_usb.h:4,                                                   from include/cc1111.h:48,
                 from include/cc1111_aes.h:7,                                                    from cc1111_aes.c:2:
include/global.h:84:1: warning: "NOP" redefined
In file included from /usr/share/sdcc/include/mcs51/cc1110.h:29,
                 from include/cc1111.h:5,
                 from include/cc1111_aes.h:7,
                 from cc1111_aes.c:2:
/usr/share/sdcc/include/mcs51/compiler.h:88:1: error: this is the location of the previous definition
```

The NOP-macros are, as one might guess, exactly the same.  (pull request soon)

### PR DESCRIPTION
**Pull request by thecubic**
This resolves #29, by wrapping the define in a conditional.

### CODE REVIEW

File: CC-Bootloader/rfcat_bootloader [hunk 1]
```diff
@@ -7,31 +7,31 @@ from serial.serialutil import SerialException
 
 
 bootloader_error_codes = {
-  '0' : "OK",
-  '1' : "Intel HEX Invalid",
-  '2' : "Bad Checksum",
-  '3' : "Bad Address",
-  '4' : "Bad Record Type",
-  '5' : "Record Too Long"
+  b'0' : "OK",
```
Comment (atlas0fd00m) [inline CC-Bootloader/rfcat_bootloader]: i appreciate the help!
two requests:
1) please split these out into two separate pull requests (when i'm contributing code, i'll create a branch in my own fork for each PR, each based on the upstream master branch.  this allows each to be evaluated and merged as "bite-sized chunks"
2) reach out to @roaldnefs , who has volunteered to create a PR for porting RfCat to use Python3 (since much of the code deltas in this PR are for Python3)

i realize this may take a little doing on your end, and i apologize.

**Review by atlas0fd00m — CHANGES_REQUESTED** [review]

**Comment by thecubic** [comment]
my bad - I was not aware pushes to branches automatically expand PRs.  I've rewound my master branch.

I have a pretty good start at a Py3 port; I just started chasing a different butterfly since about a year ago: https://github.com/thecubic/rfspy  That one can ping but I haven't implemented anything else.  I hacked on a Go client yesterday: https://github.com/thecubic/gorfcat; it can ping and enter and exit bootloader mode so far

File: firmware/include/cc2531.h [hunk 2]
```diff
@@ -46,7 +46,12 @@ SFRX(USBF5,     0x622A);        // Endpoint 5 FIFO
 // USB activities
 #define USB_ENABLE_PIN              P1_0
 //#define USB_ENABLE_PIN              P1_1
+
+// NOP macro which may be defined elsewhere
+#ifndef NOP
```
Comment (atlas0fd00m) [inline firmware/include/cc2531.h:51]: is there a central location that would work here?  global.h, assuming proper order of includes?  i hate the duplication and would avoid it if possible.
does the code compile without this one? (assuming not, but i have to ask)

**Comment by jrb** [comment]
Unless grep has let me down, it looks like `cc2531.h` is only ever included in `global.h`. ( https://github.com/atlas0fd00m/rfcat/blob/master/firmware/include/global.h#L11 ) Unfortunately `cc2531.h` uses NOOP itself once: https://github.com/atlas0fd00m/rfcat/blob/master/firmware/include/cc2531.h#L52 in USB_RESET() (which itself is duplicated over in `chipcon_usb.h`

I think at a minimum the NOOP and USB_RESET can be pulled from `cc2531.h`, and possibly a lot more.

**Comment by atlas0fd00m** [comment]
yes, it's still WIP.  it's been a while since being touched, but last i remember, i believe it compiled and allowed a basic C2 to the device.

**Comment by jrb** [comment]
it seems like the smoothest way forward on this pr might be to just live with the two NOPs wrapped in ifndefs, then create an issue to finish/rework cc2531 support? Since removing NOP from `cc2351.h` also means removing or reworking USB_RESET, it feels like a separate change set?

in my local branch, i'm working on getting builds going on 3.7.0 and 3.8.0 as well, and have just wrapped both in an ifndef, and moved on to fixing the char situation
